### ISSUE TITLE
2019/03 - SysML Conference 2019

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#100]
# 2019/03 - SysML Conference

**URL**: homepage of the conference

**Location**: Stanford, CA, USA

**Dates**: start and end dates (2018/03/31-2018/04/02)

**Expenses covered**: Maybe

**Topic**:  ML

**Call for Papers**: 

deadline: 2018/09/28

link: https://www.sysml.cc/submission.html

**Notes**:

Close to SF, maybe organize an event / meetup at the same time.

**Comment by bzz** [comment]
Shall we close it, when CfP deadline has passed?

**Comment by vcoisne** [comment]
@bzz The idea was to maybe attend and organize a meetup at the same time so I would keep it open for now

**Comment by campoy** [comment]
We should start working on this if we want to run a meetup, @vcoisne

**Comment by vcoisne** [comment]
Yes not a priority on my to-do list right now but I will try to make it happen

**Comment by vcoisne** [comment]
We had a meetup in SF at the same time.

**Comment by bzz** [comment]
🚀 I guess it's ["Code as Data workshop: get insights from git repos with SQL"](http://archive.is/WPAxI) - linking, just for the sake of history.
