### ISSUE TITLE
2019/05 - CraftConf

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#101]
**URL**: https://craft-conf.com/

**Location**: Budapest, Hungary

**Dates**: 2019/05/7-2019/05/10)

**Expenses covered**: Maybe

**Topic**:    Full stack, DevOps

**Call for Papers**:

deadline: 2018/10/15
link:  https://www.papercall.io/craft-conf-2019

**Notes**:

Your software as a crime scene was a very popular topic there. Something to think about as we work on submission.

**Comment by bzz** [comment]
Shall we close now, when CfP deadline has passed?

**Comment by vcoisne** [comment]
I think we should yes.
