### ISSUE TITLE
2019/04 - Artificial Intelligence NY (O'reilly)

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#102]
**URL**: https://conferences.oreilly.com/artificial-intelligence/ai-ny

**Location**: NYC, USA

**Dates**: 2019/04/15-18

**Expenses covered**: trip + hotel covered

**Topic**:  Machine Learning, AI, MLonCode

**Call for Papers**:

deadline: 2018/10/16
link: https://conferences.oreilly.com/artificial-intelligence/ai-ny/public/cfp/675

**Notes**:

First time applying to this one, but seen how other O'Reilly conferences work this seems like a great opportunity.

**Comment by bzz** [comment]
Seems like deadline has passed on this one as well.
