### ISSUE TITLE
2019/07 - OSCON

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#103]
**URL**: https://conferences.oreilly.com/oscon/oscon-or

**Location**: Portland, Oregon, USA

**Dates**: start and end dates (2019/07/15-18)

**Expenses covered**: Maybe

**Topic**:   Open Source

**Call for Papers**: November 2018–January 2019

deadline: 2019/01/15
link:     TBD

**Notes**:

Interesting for our Inner Source use case and Open Source Project Metrics / Analysis

**Comment by campoy** [comment]
ML on Code talk was accepted

**Comment by vcoisne** [comment]
Francesc will be mentioning sourced in this talk but not tracking any action items. Closing.
