### ISSUE TITLE
2019/05 - KubeCon EU

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#106]
**URL**: https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/

**Location**: Barcelona, Spain

**Dates**: 2019/05/20-23)

**Expenses covered**: Maybe

**Topic**:   Kubernetes, CNCF projects, Open Source

**Call for Papers**:

deadline: 2019/01/18

link:    https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/cfp/

**Notes**:

CFP Opens: Monday, October 29, 2018
CFP Closes: Friday, January 18, 2019
Schedule Announcement: Thursday, March 7, 2019

**Comment by vcoisne** [comment]
@rporres @meyskens Might be worth submitting a talk based on our internal Kubernetes use case ? 

@campoy Happy to submit a talk on your behalf about the Kubernetes Analysis we did ?

**Comment by campoy** [comment]
I'm planning on doing that this week, but if you wanna get the abstract started that'd definitely be helpful

**Comment by rporres** [comment]
@vcoisne There's nothing very special about our k8s internal case apart from the way we install it, which has already been subject of talks.

**Comment by vcoisne** [comment]
@rporres noted. 

@campoy how about the following for the abstract: 

As the Kubernetes project nears 2 million lines of code (including all languages and generated files), many users are wondering about the evolution and trends of the 4-year-old open source project overtime. The community of users is probably wondering if the project is showing signs of maturity, what are the areas under heavy development with the highest commit velocity or  who are the most active contributors. 
 
In this talk, users will learn how they can leverage the open source toolkit from source{d} to perform a language agnostic source code analysis of the Kubernetes project and extract a lot of interesting information directly from GitHub.

**Comment by vcoisne** [comment]
Talk was canceled due to Francesc leaving.
