### ISSUE TITLE
2019/02 - Git Merge

### ISSUE THREAD

**Issue by jfontan** [src-d/conferences#108]
# 2019/02 - Git Merge

**URL**: https://git-merge.com/

**Location**: Brussels, Belgium

**Dates**: 2019/02/01

**Expenses covered**: admission

**Topic**: Git

**Call for Papers**:

deadline: 2018/10/21
link: https://github.submittable.com/submit/8a716928-dcb9-427b-81e0-b9521ca7d055/git-merge-2019-call-for-proposals

**Notes**:

Initial abstract for gitbase talk:

> At source{d} we have to analyze a huge amount of git repositories and extract insights on source code. To do this have created an SQL database engine that is able to understand git repositories and is MySQL protocol compatible. We had to tackle some problems like solving the differences between git repository model and relational databases, create a database engine in go language, parallelize git repository access or finding ways to store and use caches and indexes. You'll learn about the journey from what began as a side project to the current state, its internals and the different solutions we approached.

**Comment by marnovo** [comment]
Actually the deadline is now in Oct 21!!

> Interested in speaking?
> Share your Git experience with the world. GitHub is accepting proposals to speak at Git Merge until OCTOBER 21, 2018

Well, seems I can't fight the deadline reminder bot, so @jfontan please edit your post.

**Comment by vcoisne** [comment]
@jfontan have you submitted already ? Would it be possible to make the talk more about the Engine (mentioned in the title and abstract) with a focus on Gitbase ?

**Comment by mcuadros** [comment]
The conference is about git, I rather talk more focus than broad, and generic

**Comment by jfontan** [comment]
I still have not sent anything. First I wanted you to review the abstract. I can narrow the scope to how gitbase maps git objects to tables and implementation details to make it faster. Like the squash idea of chaining iterators and indexes.

**Comment by vcoisne** [comment]
@jfontan  I think the initial scope is fine, I was only suggesting to mention source{d} Engine somewhere in the abstract. 

For example: "At source{d} we analyze a huge amount of git repositories and extract insights on source code. To do this have created source{d} Engine, a powerful engine for language-agnostic analysis of your source code and git history. The git history part of the analysis is handled by Gitbase, an SQL database engine that is able to understand git repositories and is MySQL protocol compatible. We had to tackle some problems like solving the differences between git repository model and relational databases, create a database engine in go language, parallelize git repository access or finding ways to store and use caches and indexes. You'll learn about the journey from what began as a side project to the current state, its internals and the different solutions we approached."

**Comment by jfontan** [comment]
If you agree I'll submit this next week. The title will be the same as in gitbase repo:

"gitbase, SQL interface to Git repositories"

**Comment by jfontan** [comment]
I've already submitted the proposal.

**Comment by vcoisne** [comment]
Perfect thanks @jfontan !

**Comment by vcoisne** [comment]
@campoy here is the info on sponsorship per our conversation. 

Community level is $10K and includes the following:

- Logo on signage and interstitial slides
- Logo and link on event website
- Logo in communications to attendees
- Option to add-on demo lounge or afterparty
- (3) complimentary conference badges plus 50% any additional badges (please note tickets to workshop day are separate)
- Verbal ‘thank you’ on stage
- One hour per day at the shared Demo Desk
- Option to host your own gathering before or after the event, promoted to attendees

What do you think ?

**Comment by campoy** [comment]
As discussed in person this doesn't seem to be worth it at this point.
Let's not sponsor, let's simply attend.

Let's also make sure that all of us attending the conference invite everyone to attend our devrooms and event on Saturday.

**Comment by bzz** [comment]
<img width="523" alt="screen shot 2018-11-21 at 10 25 28 am" src="https://user-images.githubusercontent.com/5582506/48831760-cd890400-ed77-11e8-9e37-83c51fa82cdd.png">

https://src-d.slack.com/archives/C3H7SF8T0/p1542714756002100?thread_ts=1542714756.002100

**Comment by campoy** [comment]
Hey @jfontan, could you add a PR with the abstract that you proposed?
Follow the instructions in the README.

**Comment by jfontan** [comment]
Done #114

**Comment by vmarkovtsev** [comment]
My talk was rejected, as it was the last year. I will keep submitting until they goddamn accept it!

BTW, there is an opportunity to save 50 bucks for a ticket by using the following promo code: `GM19THANKS `

**Comment by campoy** [comment]
That's the spirit, one day we'll get it!

**Comment by campoy** [comment]
Hey @jfontan, can you add your slides to the repo?
Also, was there any recording?

Then we can close this

**Comment by jfontan** [comment]
The recording is still not published. You can find the slides here:

https://docs.google.com/presentation/d/1DsXvoylMJ7EHGQvIU87eSptU3lJ_2f6iPcYXc7AzW70/edit?usp=sharing

**Comment by jfontan** [comment]
Here's the recording link. It's still unlisted so I don't know if it will be the final URL:

https://www.youtube.com/watch?v=f_G1vwynxTg

**Comment by bzz** [comment]
> Hey @jfontan, can you add your slides to the repo?
> Also, was there any recording?
> 
> Then we can close this

If no objections, I'm going to take a liberty and close this, as it seems like slides and recording was added by @jfontan above.
