### ISSUE TITLE
2018/06 DockerCon

### ISSUE THREAD

**Issue by bzz** [src-d/conferences#11]
# DockerCon 2018

**URL**:  - https://2018.dockercon.com

**Location**: San Francisco, US (Moscone Center)

**Dates**: 2018/06/12-15

**Expenses covered**: ?

**Topic**:   Containers, Docker, Moby

**Call for Papers**:

- deadline: 2018/01/18
- link: https://2018.dockercon.com/call-for-papers/

**Notes**:

May be relevant for src-d infrastructure efforts.

**Comment by campoy** [comment]
Proposed two talks before the CfP closed!
