### ISSUE TITLE
2018/11 - Codemotion

### ISSUE THREAD

**Issue by erizocosmico** [src-d/conferences#111]
# 2018/11 - Codemotion

**URL**: https://madrid2018.codemotionworld.com

**Location**: Madrid, Spain

**Dates**: 2018/11/30-2018/12/1

**Expenses covered**: n/a

**Topic**: general

**Call for Papers**:

Deadline already over

**Notes**:

There's a talk on how to back up large amount of Git data by someone who works at GitHub that may be interesting for us.

**Comment by bzz** [comment]
AFAIK this conference became "company-oriented" and the same organizers are now host https://2018.commit-conf.com/ on 23-24 of Nov in Madrid.

It may be very much worth attending, as this is the biggest OSS community gettogether in Spain.

**Comment by erizocosmico** [comment]
There are no more tickets available so I guess there’s no point in keeping this open.
