### ISSUE TITLE
2019/06 - Velocity San Jose

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#112]
**URL**: https://conferences.oreilly.com/vl-ca

**Location**: San Jose, CA USA

**Dates**: 2019/06/10-13

**Expenses covered**: N/A

**Topic**: 

- Cloud, Cloud Native, and Infrastructure
- Serverless
- Containers, Kubernetes, and Microservices
- Monitoring, Observability, and Performance
- SRE and DevOps
- Distributed Data and State
- Security
- Systems Engineering and Architecture
- Leadership
- Emerging Tech (Machine Learning, AI, Blockchain)

**Call for Papers**:

deadline: 2018/12/10
link: https://conferences.oreilly.com/vl-ca/public/cfp/690

**Notes**:

Easy trip and big audience, it'd be great to run keynote & workshop

**Comment by vcoisne** [comment]
@campoy this is coming up soon. Happy to submit for a talk on Code As Data or else ?

**Comment by campoy** [comment]
yup, already on my todo list for this week

**Comment by campoy** [comment]
Talk was accepted as a backup talk, so I'll leave the phase as is for now.

**Comment by vcoisne** [comment]
Francesc will be speaking there but not about sourced. Closing.
