### ISSUE TITLE
2019/12 - Kubecon / CloudNativeCon North America

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#113]
**URL**: https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2018/

**Location**: Seattle, WA

**Dates**: 2019/12/10-13

**Expenses covered**: No

**Topic**: Kubernetes and other CNCF projects

**Call for Papers**:

deadline: closed
link: n/a

**Notes**:

Many potential customers will be attending, so it seems like a great opportunity to socialize.
Tickets are really expensive though, so maybe worth trying to get a pass for the expo hall only.

**Comment by campoy** [comment]
Most source{d} employees will be at the Christmas Dinner.

**Comment by SvenDowideit** [comment]
did you mean to title this 2018/12 ?
