### ISSUE TITLE
2019/05 - DevSum

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#116]
**URL**: https://www.devsum.se/

**Location**: Stockholm, Sweden

**Dates**: 2019/05/23-24

**Expenses covered**: transportation and hotel are covered 🎉 

**Topic**: software engineering

**Call for Papers**:

deadline: 2019/01/02
(according to Sessionize; the other page says December 23rd)
link: https://sessionize.com/devsum/

**Notes**:

I read some positive feedback about this conference on the internet.

**Comment by campoy** [comment]
Hey @vmarkovtsev, let me know if the proposal is accepted.

**Comment by vmarkovtsev** [comment]
Their website says "more speakers will be announced during the spring". So I have to wait.
