### ISSUE TITLE
2019-06 ML Conference

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#122]
**URL**: https://mlconference.ai/

**Location**: Munich, Germany

**Dates**: 2019/06/17-19

**Expenses covered**: no info; the conference is paid so we should ask to provide a hotel or flights

**Topic**: ML

**Call for Papers**:

deadline: 2019/01/14
link: https://callforpapers.sandsmedia.com/

**Notes**:

Egor has spoken twice there. Seal of approval.

**Comment by m09** [comment]
As discussed I submitted a CFP

**Comment by vmarkovtsev** [comment]
@m09 Can you please create a PR with your submission, e.g. https://github.com/src-d/conferences/pull/123

**Comment by campoy** [comment]
@vmarkovtsev was accepted, any news on @m09's proposal?

**Comment by vmarkovtsev** [comment]
I checked yesterday, nothing...

**Comment by m09** [comment]
I didn't receive anything (neither refusal nor approval) so I guess it's been rejected :(

**Comment by vmarkovtsev** [comment]
They are still considering

**Comment by vcoisne** [comment]
@m09 @vmarkovtsev any update on this one ?

**Comment by m09** [comment]
I didn't receive anything so mine was refused it seems.

**Comment by vmarkovtsev** [comment]
They published the programme, mine was accepted and Hugo's effectively rejected.

**Comment by vmarkovtsev** [comment]
This happened. The slides are: http://vmarkovtsev.github.io/mlconference-2019-munich

**Comment by bzz** [comment]
As the event has happened and slides are posted, if no objections I'll be taking a liberty of closing this one.
