### ISSUE TITLE
2019/03 - dotGo

### ISSUE THREAD

**Issue by meyskens** [src-d/conferences#127]
**URL**: https://www.dotgo.eu/

**Location**: Paris, France

**Dates**: 2019/03/25

**Expenses covered**: "we may be able to cover the travel & hotel for the submissions we accept as regular slots. Selected lightning talk speakers will get a free ticket to the conference."

**Topic**: Go

**Call for Papers**: 

deadline:  6 weeks before the event for regular slots, and 2 weeks before for lightning talks
link: https://docs.google.com/forms/d/e/1FAIpQLSfJjXZDjdvJKTKUz_HedK9oJt_sh9MN57GIm_7H0MfDnd4wOA/viewform?c=0&w=1

**Notes**:

I am probably going as I got a ticket as Go Meetup organizer

**Comment by campoy** [comment]
Hey @src-d/company-wide,

I invite everyone to propose a talk for dotGo!
I'm not planning on attending this year, but I can coach you and help writing the abstract.

**Comment by vcoisne** [comment]
We missed the deadline.
