### ISSUE TITLE
2019/03 - AI & Society meetup

### ISSUE THREAD

**Issue by warenlg** [src-d/conferences#131]
**URL**: https://www.meetup.com/AI-and-society (French)

**Location**: Paris, France

**Dates**: 2019/03/04

**Expenses covered**: no

**Topic**:     3 talks around AI (1. Technology 2. Business 3. Society)
January's tech talk was about MLonCode from BeepAI

**Call for Papers**:

deadline: not specified

**Notes**:

I exchanged few mails with the organizer last week, and she would be ok to let me do the next tech talk about MLonCode/Lookout (20min + 10min Q&A)

**Comment by vcoisne** [comment]
Looks like a great opportunity to me. @campoy to confirm budget approval i.e 80 EUR

**Comment by vcoisne** [comment]
Slides have been published. Closing.
