### ISSUE TITLE
2019/10 - SPLASH OOPSLA

### ISSUE THREAD

**Issue by warenlg** [src-d/conferences#132]
**URL**: https://conf.researchr.org/track/splash-2019/splash-2019-oopsla

**Location**: Athens, Greece

**Dates**: 2019/10/20-25)

**Expenses covered**: no

**Topic**:
* Software development
* New tools (such as language front-ends, program analyses, and runtime systems)
* New techniques (such as methodologies, design processes, and code organization approaches)
* New principles (such as formalisms, proofs, models, and paradigms)
* New evaluations (such as experiments, corpora analyses, user studies, and surveys)

**Call for Papers**:

deadline: paper submission 2019/04/05)
link: https://2019.splashcon.org/track/splash-2019-oopsla

**Notes**:

One of the biggest A* conference around Software Engineering. We had a [meeting](https://github.com/src-d/minutes/pull/452/files) with the authors of the [DejaVu](http://delivery.acm.org/10.1145/3140000/3133908/oopsla17-oopsla176.pdf?ip=83.35.2.107&id=3133908&acc=OA&key=4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2EC1E31BC46E58D5B8&__acm__=1548776578_a78ebccc262c757047e394d7a8494a4f) project (academical reference in terms of code deduplication). They would like to collaborate on a new project that aims to trace the life-cycle of code clones in OSS https://github.com/PRL-PRG/dejavuii/blob/master/docs/plan.md, and pulish the paper to this conference.

**Comment by vcoisne** [comment]
@warenlg sorry I did not see this earlier. Looks like the deadline has passed for CFP. Seems like an interesting collaboration though. What does @vmarkovtsev thinks about this ?

**Comment by vmarkovtsev** [comment]
Yes, we should consider submitting a paper next year. We decided to go with [ML4SE](https://ml4se.github.io) this time since it was much lighter.

**Comment by warenlg** [comment]
ok, let's remember this one for next year

**Comment by bzz** [comment]
Taking liberty of closing this, as soon as there is no further discussion, and the consensus seems to be that we apply next year which most probably is going to happen in a separate issue.
