### ISSUE TITLE
2019/05 - PyDays Vienna

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#133]
**URL**: https://www.pydays.at/

**Location**: Vienna, Austria

**Dates**: 2019/05/03-04

**Expenses covered**: no

**Topic**:  Python + special track for ML

**Call for Papers**:

deadline: 2019/03/25
link:     https://www.pydays.at/cfp/

**Notes**:

I and @warenlg participated last year: https://github.com/src-d/conferences/issues/59
The greatest feature was very good reception. Besides, there was a special track of talks about ML.
Most of the attendees are students of the local university.

This is a good conference for beginners: cozy, technical, people are not spoilt.

**Comment by vcoisne** [comment]
I don't think it's an event we should prioritize. Seems like we missed the deadline anyways.

**Comment by irinakhismatullina** [comment]
No we didn't miss it, I [applied](https://github.com/src-d/conferences/blob/master/2019-pydays-vienna/typos-correction-with-lookout.md) and my talk was [accepted](https://github.com/src-d/conferences/blob/master/2019-pydays-vienna/typos-correction-with-lookout.md). The proposal was approved by Francesc and Vadim and discussed in the corresponding PR #134.

- The conference is on **3-4th of May**.
- My talk is [scheduled](https://www.pydays.at/schedule/) on **10 AM 4th of May**.
- It is free entry, but expenses are not covered. So I will need 
1. ticket Moscow - Vienna ~ 120 euros on the morning of 3th of May.
2. (at least) one night stay in Vienna ~ Not sure yet what to look for and where, it's my first conference in the company
3. _ticket Vienna - Moscow ~ 160 euros if I hurry like hell to the airport right after the talk, or more then 200 afterwards._
 I plan to stay in Europe for a week afterwards, so it would be nice to have the backward ticket on that time and not right after the conference.  Is it possible? I will book it myself and if it's more expensive then the one from Vienna right after the conference I will compensate the difference of course.

@vmarkovtsev @estherrgarcia PTAL and tell me what should I do next and what I missed so far.

**Comment by estherrgarcia** [comment]
Ticket Moscow - Vienna + accommodation done

**Comment by bzz** [comment]
@irinakhismatullina how was it? Hope it was great success this year again 🎉 .

Sorry if I have missed it, but would you be so kind to please please post the link to the slides/video/any other materials from the conference that @vcoisne could use? Thanks!

I belive after that we should be good to close this one!

**Comment by vcoisne** [comment]
ping @irinakhismatullina

**Comment by irinakhismatullina** [comment]
It was indeed nice. Though they gave me the earliest slot in the morning, so there were not so many people listening. But I think it was good for the first talk, and the orgs and the audience were super supportive and engaged.

Here are the [slides](https://irinakhismatullina.github.io/2019-vienna-pydays/). They didn't record video, so I think that's all I can provide.

**Comment by vcoisne** [comment]
Thank you @irinakhismatullina !
