### ISSUE TITLE
2019/04 - GothamGo

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#135]
**URL**: http://gothamgo.com/

**Location**: NY, USA

**Dates**: 2019/04/12

**Expenses covered**: flight + hotel covered

**Topic**:  Go

**Call for Papers**:

deadline: closed
link:  n/a

**Notes**:

**Comment by campoy** [comment]
Similarly to GOTO, if we cover the flight and hotel they would give us a Bronze sponsorship level.
What do you think @vcoisne?

**Comment by vcoisne** [comment]
+1 worth accepting the offer IMO. @campoy I can help schedule a talk at a local NYC meetup at the same time to make it even more interesting in terms of ROI.

**Comment by bzz** [comment]
As soon as there is no further discussion and it's been more than 1 month since the event, I'll take a liberty and close this one.
