### ISSUE TITLE
2019/03 - KTH

### ISSUE THREAD

**Issue by m09** [src-d/conferences#137]
**URL**: https://www.kth.se/en

**Location**: Stockholm, Sweden

**Date**: 2019/03/26

**Expenses covered**: no

**Topic**: source{d} stack and ML team projects

**Call for Papers**: N/A

**Notes**:

The talk will be part of the collaboration visit with Martin Monperrus' lab (KTH).

**Comment by vcoisne** [comment]
Sorry I did not get back to you earlier @m09. Assuming this did not happen ?

**Comment by m09** [comment]
It did as part of my visit to KTH https://github.com/src-d/minutes/pull/524

**Comment by bzz** [comment]
Taking a liberty of closing this one it has already happened and there is no further discussion.
Thank you @m09 for minutes with followup!
