### ISSUE TITLE
2019/04 - DevPRO

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#138]
**URL**: https://devpro.io/

**Location**: Tomsk, Russia

**Dates**: 2019/04/27-28

**Expenses covered**: yes!

**Topic**:  regular sw/dev

**Call for Papers**:

deadline: N/A 
link: https://devpro.io/#program

**Notes**:

Contacted directly by the organizers.

**Comment by vcoisne** [comment]
Done. Closing.
