### ISSUE TITLE
2019/10 Apache Con EU, Berlin

### ISSUE THREAD

**Issue by bzz** [src-d/conferences#142]
**URL**: https://aceu19.apachecon.com

**Location**: Berlin, Germany

**Dates**: 2019/10/22-24

**Expenses covered**: No.  (~300e on airplane + hotel)

**Topic**: Cloud, BigData, ML, 

**Call for Papers**: 

deadline: 2019/05/26
link:  https://aceu19.apachecon.com/call-presentations

**Notes**:

I'm helping to organize one of the tracks at this conference and was invited as an ASF project contributor so submit something as well. I have also invited Apache Superset (incubating) project members and they have submitted a talk to the BigData track as well.

This is an engineering conference and could be a good opportunity for us to share the work on CE that we are doing using Apache Superset with ASF community, by [analyzing some of the ASF source code](https://github.com/src-d/minutes/pull/485/files#diff-5c1fea60b8f1679f66a989b45ee2caa7R63).

**Comment by bzz** [comment]
Submitted initial proposal just to reserve the spot in #143.

If anybody is interested in being a co-speaker and present this talk together - please let me know, I'm very open! It could be a great option to start doing public speaking, as it's much less intimidating and more fun than doing it all alone.

**Comment by se7entyse7en** [comment]
I'd be glad to be co-speaker for a talk about our use case of Apache Superset!

**Comment by vcoisne** [comment]
Great idea @bzz ! Let me know once you here back + add to the event calendar please

**Comment by bzz** [comment]
Was not accepted - the whole conference ended up having only 8 talks in total for the whole BigData track.

@se7entyse7en I suggest us still working on preparing materials for such talk in background and using it for another conference.

Closing this issue for now
