### ISSUE TITLE
2019/11 - GitHub Universe

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#144]
**URL**: https://githubuniverse.com/

**Location**: San Francisco, USA

**Dates**: 2019/11/13-14)

**Expenses covered**: Maybe

**Topic**: Topic of the conference: Git, Software Development

**Call for Papers**: 
Deadline: 2019/06/17
Link: https://github.submittable.com/submit/141371/github-universe-2019-call-for-proposals

**Notes**:

Would be great to organize an Executive event at the same time!

**Comment by bzz** [comment]
From this year's guideline

> Our theme this year focuses on GitHub’s interconnected community. We want to hear stories from developers, open source maintainers, teams, and enterprises on how collaboration turns ideas into innovations. 
> Tell us about the collaborative projects you’re working on and the tools, systems, and processes you’re using to build them and iterate. Tell us about your community and how opportunities have arisen through collaboration. Teach us your best practices and how you’ve succeeded implementing GitHub at scale, managing open source security challenges, navigating a growing open source project, and more. 

Will think on what part of src-d story/stack could be a good fit for this conference.

**Comment by bzz** [comment]
I'm sorry, I was not able to come up with much this time.
