### ISSUE TITLE
2019/10 - AIDEVWORLD

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#145]
**URL**: https://aidevworld.com/

**Location**: San Jose, CA

**Dates**: 2019/10/08-10

**Expenses covered**: maybe 

**Topic**: ML, Enterprise

**Call for Papers**: 

deadline: 2019/06/14
link:     https://aidevworld.com/conference/apply-to-speak/

**Notes**:

Anything else that might be interesting for someone trying to evaluate whether this
conference is worth applying to. Were you invited? Do you know the organizers?

**Comment by bzz** [comment]
@vcoisne @dmitryvinn as the deadline has passed - did we end up submitting anything here, or shall we close it?

**Comment by vcoisne** [comment]
I think @vmarkovtsev submitted ?

**Comment by vmarkovtsev** [comment]
I think I did not find time to apply there :disappointed:

**Comment by bzz** [comment]
So, shall we close this one then, or do we have any other plans to engage @vcoisne ?

**Comment by vcoisne** [comment]
Closing.
