### ISSUE TITLE
2019/11 - Open Data Science Conference

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#146]
**URL**: https://odsc.com/london

**Location**: London, UK

**Dates**: start and end dates (201/11/19-22)

**Expenses covered**: No

**Topic**:     topic of the conference: ML, Data Science

**Call for Papers**: 

Deadline: 2019/06/31

link:     https://docs.google.com/forms/d/e/1FAIpQLScli1CPUVamej1Wb2WhXa3q4jYkzv95TXd2ddalzIVKd6WV4w/viewform

**Notes**:

Relevant for Enterprise sales

**Comment by vmarkovtsev** [comment]
I tried to speak there 2 times, and they did not accept me. Well, who knows, maybe I will have better luck this time.

**Comment by bzz** [comment]
@vmarkovtsev oh, wow! Did you end up submitting any proposal this time as well?

Seems like the deadline for CfP has passed now.

**Comment by vcoisne** [comment]
Ping @vmarkovtsev did you end submitting?

Would be great to get someone to present there if not this edition, the next one in Boston. 

cc @warenlg ?

**Comment by vmarkovtsev** [comment]
I submitted something smart, and they did not notify me of rejection, again :)

**Comment by warenlg** [comment]
I haven't submitted anything given Vadim's feedback

**Comment by bzz** [comment]
Going to close this one, as no one seems to be presenting or attending this time.
