### ISSUE TITLE
2019/07 - Skyhacks

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#148]
*URL**: https://github.com/SkyhacksPL/Talks https://www.facebook.com/events/2260432254015521

**Location**: Gliwice, Poland

**Dates**: 2019/07/15

**Expenses covered**: the hotel is covered

**Topic**: ML

**Call for Papers**:

deadline: N/A
link: N/A

**Notes**:

Contacted directly by the organizers. 500 attendees o_O

**Comment by vcoisne** [comment]
@vmarkovtsev sorry I did not see this earlier. Please tag or assign to me so that I can review on time.

Did you end up submitting?

**Comment by vmarkovtsev** [comment]
Yes, the [referenced PR linked to this issue](https://github.com/src-d/conferences/pull/149) tracks my submission.

**Comment by bzz** [comment]
As the event has happened 🎉 and sliders published at http://vmarkovtsev.github.io/mlconference-2019-munich I'll take a liberty and close this one.
