### ISSUE TITLE
2019/10 - Devfest Nantes

### ISSUE THREAD

**Issue by m09** [src-d/conferences#150]
**URL**: https://devfest.gdgnantes.com/

**Location**: Nantes, France

**Dates**: 2019/10/21-22

**Expenses covered**: only for keynote speakers I think.

**Topic**: general conference

**Call for Papers**: 

deadline: 2019/06/30
link: https://conference-hall.io/public/event/o2j0dYZDa0W1Ils3kO0z

**Notes**:

Biggest Devfest in Europe if I'm not mistaken. I already organized a codelab there and the event was nice.

**Comment by m09** [comment]
Accepted :tada: :champagne: :rocket:

**Comment by bzz** [comment]
The schedule has bee announced https://devfest.gdgnantes.com/sessions/understand_your_code_with_machine_learning_on_source_code/

**Comment by bzz** [comment]
@m09 as I'm AFK now, would you be so kind to link a gdoc with the recent meeting "minutes" and a preliminary action plan for preparing this one here please? :pray:

**Comment by bzz** [comment]
Today's workshop planing meeting followup is available [here](https://docs.google.com/document/d/1671ApmxFCOmerVKloVC6Q6j8BsJr8xZHbhuE40ZK-as/edit#).

**Comment by bzz** [comment]
All the materials and the initial prep work is handled under https://github.com/mloncode/devfest2019-workshop

**Comment by bzz** [comment]
![2019-10-24](https://user-images.githubusercontent.com/5582506/67513857-00303080-f69c-11e9-91ec-bef011b64652.jpg)

The conference was huge! 🙇 @m09 @EgorBu 

Done, closing as all materials are on GH repo.
