### ISSUE TITLE
2019/11 - Data Natives

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#151]
**URL**: https://datanatives.io/

**Location**: Berlin, Germany

**Dates**: 2019/11/25-26

**Expenses covered**: no

**Topic**:  ML, AI

**Call for Papers**:

deadline: 2019/07/01
link: https://datanatives.typeform.com/to/lOn3XI

**Notes**:

I spoke there two years ago. The organizers contacted me and I've submitted a talk today.

**Comment by vmarkovtsev** [comment]
TODO: turn this into an issue

### Title

On the road to shared ML infrastructure

### Abstract

Summary of our experience with constructing and maintaining a machine learning infrastructure for the R&D team. Constrained resources, Docker, Kubernetes, and you. How we solved the problems, e.g. GPU overcommitting for JupyterLab. What's the difference between a research environment and a production environment. Evolution of the workflow management.

**Comment by vcoisne** [comment]
@vmarkovtsev sorry I did not see this earlier. Please tag or assign to me so that I can review on time. 

Did you end up submitting ?

**Comment by vmarkovtsev** [comment]
I got a preliminary acceptance, and I am talking with the organizers today.

**Comment by vmarkovtsev** [comment]
@vcoisne Let's remove the "accepted" label for now. They have not contacted me since that call, and I am not mentioned in the list of speakers. There were two options for me: to sponsor them or to become a woman, I rejected both :(

**Comment by vcoisne** [comment]
Removed @vmarkovtsev

**Comment by vmarkovtsev** [comment]
I am silently rejected.

**Comment by vcoisne** [comment]
Ok closing then
