### ISSUE TITLE
2019/09 - UseData Conf 2019

### ISSUE THREAD

**Issue by EgorBu** [src-d/conferences#153]
**URL**:  https://usedata.ru/2019

**Location**: Moscow, Russia

**Dates**: 2019/09/16

**Expenses covered**: should be no expenses for me (live in Moscow)

**Topic**:    ML

**Call for Papers**:

deadline: 2019/07/16
link:     https://conf.ontico.ru/lectures/propose?conference=ds2019

**Notes**:

They have a person from JetBrain in the program committee. The conference focus is on applied ML

**Comment by vcoisne** [comment]
@EgorBu sorry I did not see this earlier. Please tag or assign to me so that I can review on time.

Did you end up submitting?

**Comment by EgorBu** [comment]
@vcoisne , yes, I submitted a talk and had 1 discussion last week with one person from the review committee.
This guy is from JetBrains - so he likes the talk. They should send a decision by August, 16.

**Comment by EgorBu** [comment]
The talk was accepted.

**Comment by vcoisne** [comment]
@EgorBu looks like the talk was today! Hope it went well. Are the materials in English or Russian?

**Comment by EgorBu** [comment]
Yes, the talk went really well, a lot of people interested in what we are doing) and materials are available [here](https://egorbu.github.io/usedata_2019/)

**Comment by vcoisne** [comment]
Thank you @EgorBu promoted via newsletter and social media.
