### ISSUE TITLE
2019/12 ML Conference

### ISSUE THREAD

**Issue by warenlg** [src-d/conferences#154]
**URL**: https://mlconference.ai/

**Location**: Berlin, Germany

**Dates**: start and end dates (2019/12/09-11)

**Expenses covered**: Conference paid, and I can stay at Manu's (former source{d} intern living in Berlin), so only the flights.

**Topic**: The major of the talk is *Machine Learning Business & Strategy*

**Call for Papers**:

I submitted a talk at the last moment, the day of the deadline. The talk has been accepted, here is the schedule https://mlconference.ai/program/

**Notes**:

I plan to explain how we detect Eng. teams among one codebase using developer similarity clustering and then show source{d} product by demonstrating how this becomes useful when we want to break down code metrics per team.

**Comment by vmarkovtsev** [comment]
@dmitryvinn Please, when do we switch from GitHub issues to something more convenient :sob:

**Comment by bzz** [comment]
@warenlg could you also please PR the [CfP proposal](https://github.com/src-d/conferences#tracking-call-for-papers) and link it to this thread, so the good work does not get lost?

**Comment by warenlg** [comment]
https://github.com/src-d/conferences/pull/156

**Comment by bzz** [comment]
Closing as talk has successfully happened at https://mlconference.ai/machine-learning-business-strategy/how-to-identify-collaborators-in-large-codebases-using-unsupervised-learning/

@warenlg great job! If there are any slides/other materials you could share - please, feel free to link those in here, for the history as well.

**Comment by vcoisne** [comment]
All done.
