### ISSUE TITLE
2019/10 PyconES 2019 (Alicante)

### ISSUE THREAD

**Issue by Guillemdb** [src-d/conferences#159]
# 2019/10 PyconES 2019 (Alicante)

**URL**: https://2019.es.pycon.org/

**Location**: Alicante, Spain

**Dates**:  2019/10/04 -2019/10/06

**Expenses covered**: None. I paid everything with my own money.

**Topic**:  Python, with a conference track about data science.

**Call for Papers**:
I got a workshop accepted. It will be an introductory workshop to data science (2h45min). You can find the material [here](https://github.com/PyDataMallorca/PyConES2019_Aprendiendo_como_aprenden_las_maquinas).

deadline: Closed months ago
link: https://2019.es.pycon.org/static/pdf//agenda_sabado_2.pdf (Saturday morning, taller 2)

**Notes**:

I prepared this as a hobby with other co-organizers of the PyData Mallorca meetup, and @vmarkovtsev  told me to open an issue here. 

I know the organizers of the conference, the representatives of most of the sponsors, and pretty much everyone who is relevant in the Spanish Python community.

**Comment by vcoisne** [comment]
Thank you @Guillemdb I added to the calendar and newsletter. We'll also promote on social media.

**Comment by vcoisne** [comment]
Past event.
