### ISSUE TITLE
2018/04 PyData London

### ISSUE THREAD

**Issue by warenlg** [src-d/conferences#18]
**URL**: https://pydata.org/london2018/

**Location**: London, UK

**Dates**: 2018/04/27

**Expenses covered**: 

Registration will be complimentary for speakers. If it's like PyData Warsaw, trip and accommodation are not covered. But I have friends and family there who would be pleased to host me.

**Topic**: everything that combines Python and any type of Data Science

**Call for Papers**: 

deadline: 2018/03/02
link: https://pydata.org/london2018/cfp/

**Notes**:

At the invitation of the organizers, I went to Pydata Warsaw last October and talked about https://warenlg.github.io/pydata-warsaw-2017/
This time I could either talk about my shell-completion project in Python, or the MSR dataset we are about to release with the corresponding paper. How to use our tools (engine, enry, babelfish, ml, ... ) on this specific 3T dataset of 150k repos.

**Comment by vmarkovtsev** [comment]
@warenlg You should apply tomorrow in any case.

@campoy Review ping.

**Comment by warenlg** [comment]
# Neural Shell Completion: Deep Learning approach to improve your shell

## Abstract (400 characters)

Almost all developers use a terminal and command lines they write follow strong patterns. After gathering a dataset of histories, neural networks can be trained to accelerate your shell scripting by correcting misprints and predicting your next command based on your history. This talk also describes a full deep learning project written in Python from the data collection to the RNN implementation.

## Description

This talk follows the architecture of the [shell-complete](https://github.com/src-d/shell-complete) project, detailing the key points:

2. Build the dataset of 10K command line histories
    * Get the list of repositories with the [GitHub REST API](https://developer.github.com/v3/)
    * Scrap the command histories using [scrapy](https://scrapy.org/)
    * standardize contents from **bash/fish/zsh** histories.  
  
2. Process the data and implement specific neural networks that best suit the task
    * Efficient prefix storing in tries with [pygtrie](https://github.com/google/pygtrie)
    * Build the vocabulary of command lines based on **TF-DF** best prefixes
    * For the prediction task, implement a prefix based sequential model using [Keras](https://keras.io/)
    * Incorporate artificial spelling mistakes and train a **charRNN** to autocorrect them

3. Question the user experience in a real shell
    * Current beta version is a **dockerized** service
    * Further thoughts on improving developers' use cases

**Comment by warenlg** [comment]
@campoy @vmarkovtsev here is my proposal for this 30min talk, according to their CFP format.
The deadline is gonna be tomorrow, may I apply ?

**Comment by campoy** [comment]
Please, apply

This is a very interesting talk. Have you considered writing a blog post with the same content?
Also, please send a PR with the abstract following the instructions in `README.md`.

Thanks

**Comment by warenlg** [comment]
@campoy, the talk has not been accepted. However, I'd love to write a blog post about it, and keep submitting this talk to other conferences

**Comment by campoy** [comment]
YES! Let's write a blog post about this 😄 

Let's meet online this week and discuss the contents of the post so you can get started with an initial draft.
