### ISSUE TITLE
2018/03 GopherCon Russia

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#19]
**URL**: https://www.gophercon-russia.ru/

**Location**: Moscow, Russia

**Dates**: 2018/03/17

**Expenses covered**: transportation and hotel

**Topic**: Go

**Call for Papers**: N/A
Submit proposals through hello@gophercon-russia.ru

**Notes**:
We know Alexey, one of the organizers.

**Comment by campoy** [comment]
Please add deadline for the Call for Papers

**Comment by vmarkovtsev** [comment]
@campoy It does not exist [redacted]

**Comment by campoy** [comment]
Oh, ok then. Do you know if there's any, even unofficial, date when papers are expected? if not it's fine

**Comment by vmarkovtsev** [comment]
No idea, really. The only info I have is the official website.

**Comment by vmarkovtsev** [comment]
Feedback: https://docs.google.com/spreadsheets/d/1giLDQwTTQzP2R2Qser0EbE26uv0FHIKTZglD8qbsTj0/edit#gid=0
I asked the organizers how to interpret that and they wrote they had no idea. I can conclude that the overall impression was positive; some people were apparently buried in the ML part, since it is much harder for students than devops/best practices, and the ML hype has just started in Russia.
