### ISSUE TITLE
Difference between a PR and an issue

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#2]
The current README states that one needs to submit a PR with a file under a certain directory, and an issue which is linked to the PR. Both the file and an issue share much common information; what's the difference between them?

**Comment by campoy** [comment]
Let me know if this is enough.
I'll also do it for GopherCon as an example (I've already been accepted)

**Comment by campoy** [comment]
You can look at what a CfP plus proposal look like at https://github.com/src-d/conferences/issues/4 and https://github.com/src-d/conferences/pull/5
