### ISSUE TITLE
2018/03 Developer Relations Conference - Palo Alto

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#23]
**URL**: https://evansdata.com/drc/2018/index.php

**Location**: Palo Alto, USA

**Dates**: 2018/03/26-27

**Expenses covered**: none

**Topic**:  Developer Relations

**Call for Papers**: N/A

**Notes**:

Considering attending as many important people in Developer Relations will be there.
Cost is USD 1,095.00

**Comment by campoy** [comment]
I think I should attend this conference, it is a bit pricey but at least travel cost is zero since I can take CalTrain to get there.

What do you think, @eiso?

**Comment by eiso** [comment]
Discussed in person: yes.

**Comment by campoy** [comment]
I should ask Sam Ramji whether I can get a ticket from him

**Comment by vmarkovtsev** [comment]
@campoy LOL

**Comment by campoy** [comment]
Well, that's a bug in the reminder 🤦‍♂️
