### ISSUE TITLE
2018/03 FOSSASIA '18

### ISSUE THREAD

**Issue by bzz** [src-d/conferences#29]
**URL**: https://2018.fossasia.org/

**Location**: Singapore, Singapore.

**Dates**: 2018/03/22-25

**Expenses covered**: N/A

**Topic**: 
 - Machine Learning and AI
 - Open Design, IoT, Hardware, Imaging
 - Science, Tech and Education
 - Kernel and Platform
 - Database
 - Cloud, Container, DevOps 
 - Open Data, Internet Society, Community
 - Open Event Solutions
 - Cybersecurity
 - Web and Mobile
 - Open Source in Business
 - Blockchain

**Call for Papers**:

deadline: N/A
link:     https://eventyay.com/e/b548bcfc/cfs/

**Notes**:

This is a FOSDEM of Asia - the biggest international Open Source event in Asia.

Very close relationship with organizers: for last 3 years [Alex helps organizing it](https://fossasia.org/team): i.e in '17 hosted an Open Source Design track and did a talk in ML track about source{d} ML paper on Topic Modeling.

**Comment by bzz** [comment]
This year I was asked to moderate whole ML&AI track (schedule is being finalized now) and present on source{d} progress with MLoSC (in front of few hundreds audience).

The talk `"Machine Learning on Source Code (MLoSC): OSS stack and applications"` has been accepted.

If supported, I plan to talk about source{d} tech stack, by telling a story of how all parts of the stack fit together on:
 - either a real application that we have of gemini/apollo, 
 - or based on next stage of ML research (after Topic Modelling)-  `id2vec`

covering
 - sourced.ml
 - bblfsh
 - engine
 - gemini/apollo

The only support needed is ✈️ and 3 night 🏨

**Comment by vmarkovtsev** [comment]
Congrats! Please adjust the title to Machine Learning **on** Source Code - this is as it goes in the papers.

We are writing a paper about id2vec - https://github.com/src-d/backlog/issues/1166 so I think it is better to go with it. Apollo paper is only planned and the research itself is far from being complete.

@zurk is seeking for "toy problems" to benchmark the quality of embeddings, so you could collaborate. Also is a great use case of the dataset we have (almost) collected.

**Comment by zurk** [comment]
Yes, everything is right. 
Any help and ideas with "toy problems" to test our embeddings are appreciated. 
Now I research literature to find what people usually do in embedding world. It will be different for us, since (almost) nobody does something like that for source code analysis as far as I know. 

**(Update)** I create a raw list of what I what to try while playing with embeddings.
https://github.com/src-d/backlog/issues/1166#issuecomment-363476976

**Comment by bzz** [comment]
As discussed with @campoy - the only concern is if traveling that far it would make sense to have anther event. 

To address it, I plan to schedule a meetup on the side, most probably with a workshop on "hands on on MLoSC stack".

As discussed with @eiso that should work, so waiting for confirmation from @campoy .

**Comment by campoy** [comment]
SGTM

**Comment by campoy** [comment]
(that's why I set the label `phase:accepted`)

**Comment by bzz** [comment]
:+1: Thank you @campoy !

Going to proceed with visa,  🛩 and 🏨.

**Comment by bzz** [comment]
The talk and workshop went very well, workshop materials are in https://github.com/bzz/ml-on-code and ["Machine Learning on Code: OSS Stack for Research & Development"](https://docs.google.com/presentation/d/1M94zELEaK1gq4aVdME60AVqSRiq77NY49fqctQMIEbc/edit) talk slides are available.

**Comment by campoy** [comment]
Please make sure you update the proposal with a link to the materials.
