### ISSUE TITLE
2018/10 - GoLab

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#33]
**URL**: https://golab.io/

**Location**: Florence, Italy

**Dates**: 2018/10/22-23

**Expenses covered**: no

**Topic**: Go

**Call for Papers**:

deadline: 2018/04/04
link: https://www.papercall.io/golab2018

**Notes**:

Found out about it on FOSDEM... Was it Francesc who told me?

**Comment by campoy** [comment]
Let's work on the talks, the previous edition was far from perfect and the recordings were not very high quality, which kinda makes me wonder whether this is a good conference to attend

on the other hand it's a short trip from Madrid
