### ISSUE TITLE
2018/06 - PyCon CZ

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#35]
**URL**: https://cz.pycon.org/2018/

**Location**: Prague, Czech Republic

**Dates**: start and end dates 2018/06/01-03

**Expenses covered**: no

**Topic**:  Python

**Call for Papers**:

deadline: 2018/02/28
link: https://cz.pycon.org/2018/proposals/

**Notes**:

Saw the advertisement at FOSDEM.

**Comment by campoy** [comment]
This seems like a great conference, nice mix of speakers and caring about diversity.
Plus professional recordings for all talks!

Definitely worth the trip
