### ISSUE TITLE
2018/08 - GopherCon Denver

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#4]
**URL**: https://www.gophercon.com/

**Location**: Denver, USA

**Dates**: 2018/08/27-30

**Expenses covered**:

Travel Assistance - Yes
We offer flight and hotel assistance to speakers who would not otherwise have their travel sponsored by an employer. All speakers will also receive one general admission ticket to the conference and an invitation to the VIP/Speaker dinner during the conference.

**Topic**:   Go

**Call for Papers**:

deadline: 2018/03/15
link: https://www.papercall.io/gophercon2018

**Notes**:

Seems like a good opportunity to present our way of using Go.
Francesc will attend for sure and it might be a good opportunity to get a lot of visibility.

Should we sponsor?

**Comment by campoy** [comment]
We should attend this conference, moving to `open`.

**Comment by eiso** [comment]
Regarding sponsorship, we need to define a strategy. My first intuition is usually to designate that money to more worthwhile efforts then lining the pockets of conference organisers to have a logo on the wall. e.g. Providing scholarships for people to go to the actual conference

**Comment by campoy** [comment]
Maybe we could collaborate with Women Who Go and sponsor some tickets!
