### ISSUE TITLE
2018/06 - DeveloperWeek NY

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#42]
**URL**: http://www.developerweek.com/NYC/

**Location**: New York, USA

**Dates**: 2018/06/18-20

**Expenses covered**: not clear yet, GDE should cover.

**Topic**: Software Development; AI; management

**Call for Papers**:

deadline: 2018/03/05
link: http://www.developerweek.com/NYC/conference/apply-to-speak/

**Notes**:
Found almost at random in Dec 2017 as a conference related to ML.

**Comment by campoy** [comment]
Hey @vmarkovtsev 

Please next time let me know before you actually send a talk
I don't know anything about this conference

**Comment by vmarkovtsev** [comment]
@campoy Back then we did not have this repo, so I filed an issue in devrel: https://github.com/src-d/devrel/issues/26
