### ISSUE TITLE
2018/07 - PyCon Russia

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#49]
**URL**: http://pycon.ru/2018/

**Location**: Moscow, Russia

**Dates**: 2018/07/22-23

**Expenses covered**: no

**Topic**: Python and this means ML too

**Call for Papers**:

deadline: 2018/06/12
link: http://pycon.ru/2018/program/speakers/

**Notes**:

Vadim applied two times in the past, they rejected.

**Comment by campoy** [comment]
I'm assuming this wasn't accepted.
