### ISSUE TITLE
2018/07 - Scalapeño

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#53]
**URL**: https://www.scalapeno2018.com/

**Location**: Beersheba, Israel

**Dates**: 2018/07/02

**Expenses covered**: nope

**Topic**: Scala

**Call for Papers**:

deadline: 2018/04/01
link: https://docs.google.com/forms/d/e/1FAIpQLSdG__usIvUxXzuSO7qGtmF97ktPzRRR9mx6Me-0XiHWE0XMCQ/viewform

**Notes**:

Super cool design.

**Comment by campoy** [comment]
Closing, as we didn't send any proposals
