### ISSUE TITLE
2018/05 - OSCAL

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#57]
**URL**: https://oscal.openlabs.cc/

**Location**: Tirana, Albania

**Dates**: 2018/05/19-20

**Expenses covered**: no

**Topic**: Open Source

**Call for Papers**:

deadline: 2018/04/01
link: https://docs.google.com/forms/d/e/1FAIpQLSfNZN8DtwBKu-Va38q7KqYZbkVv7GrxpSctcIB1FIiE_iurVg

**Notes**:

Found this thanks to @bzz's retweet

**Comment by vmarkovtsev** [comment]
Accepted: https://oscal.openlabs.cc/speakers/vadim-markovtsev/

**Comment by vmarkovtsev** [comment]
It is completely unexpected that they accepted both talks, so god please help me.

**Comment by bzz** [comment]
@campoy shall this one be closed now?
