### ISSUE TITLE
2018/04 DEVOPS.BCN

### ISSUE THREAD

**Issue by mcuadros** [src-d/conferences#6]
# DEVOPS.BCN 2018

**URL**: https://devops.barcelona

**Location**: Barcelona, Spain

**Dates**: 2018/04/10-12

**Expenses covered**: fees covered for speakers: transportation, hotel, etc

**Topic**:  Infrastructure, Configuration Management

**Call for Papers**:

- deadline: 2018/01/31
- link:     https://devops.barcelona/call-for-papers

**Comment by rporres** [comment]
I've sent the same talk that was accepted in the configuration management camp: http://cfgmgmtcamp.eu/schedule/terraform/CoreOS.html

**Comment by campoy** [comment]
Thanks @rporres, would you mind creating a PR with the abstract etc so we can keep track?
Thanks!
