### ISSUE TITLE
2018/04 - Retina

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#62]
**URL**: https://retina.elpais.com/

**Location**: Madrid, Spain

**Dates**: 2018/04/25

**Expenses covered**: no

**Topic**:  Google awesomeness

**Call for Papers**:

deadline: don't know
link: N/A

**Notes**:

The organizers from Google contacted Máximo. There was a meeting on which they described the requirements:
- Audience is developers, PMs and business people
- Case studies in ML/Cloud with Google
- Length less than 30 min
- Google Slides

**Comment by campoy** [comment]
Is this organized by Google? Should we talk to the organizers?

**Comment by campoy** [comment]
In the future, make sure you add deadlines to conferences.
If none is available use the date of the conference.

**Comment by vmarkovtsev** [comment]
@campoy This is a past event. Vueling pilots had a strike so Egor spoke instead of me.

Summary: available by request in DM.
