### ISSUE TITLE
2018/10 - GitHub Universe

### ISSUE THREAD

**Issue by mcuadros** [src-d/conferences#65]
# 2018/10 - GitHub Universe

**URL**: https://githubuniverse.com/

**Location**: SFO
**Dates**: start and end dates (2018/10/16-17)

**Expenses covered**: Yes

**Topic**:  Generalistic
**Call for Papers**:

deadline:  2018/06/01
link: https://github.submittable.com/submit/110757/github-universe-2018-call-for-proposals

**Notes**:
Maybe I am thinking on attend since I will be in SFO the week before attending HashiConf

**Comment by campoy** [comment]
Updated deadline (it was in 2017!)
