### ISSUE TITLE
2018/10 - HashiConf 2018

### ISSUE THREAD

**Issue by mcuadros** [src-d/conferences#66]
# 2018/10 - HashiConf 2018

**URL**: https://www.hashiconf.com/
**Location**: SFO

**Dates**: 2018/10/22-24

**Expenses covered**: Maybe

**Topic**:  Infra

**Call for Papers**:

deadline: 2018/07/01
link: https://www.hashiconf.com/call-for-proposals.html

**Notes**:
I am attending as a contributor to Terraform. 

/cc @rporres maybe you can send your talk here (with some updates)

**Comment by rporres** [comment]
Let's talk about the updates you're thinking about, @mcuadros 😏

**Comment by campoy** [comment]
updated deadline (it was incorrectly formatted)

**Comment by campoy** [comment]
Do you think you'd be able to give a talk? It's always worth trying and I'm happy to collaborate (even get on stage with you!)

**Comment by mcuadros** [comment]
Yep I think @rporres can give a talk, not many people are speaking about baremetal and coreos, so I think worth to try it.

**Comment by campoy** [comment]
The deadline is in a couple weeks, happy to review any proposal before they're send to the CfP.
@mcuadros @rporres

**Comment by rporres** [comment]
Deadline has been extended to 16th of July. I was thinking on submitting the [talk](https://github.com/src-d/conferences/blob/master/2018-cfgmgmtcamp/coreos-baremental-provisioning-terraform.md) I gave on Configuration management camp. Most likely it would be nice to do a proper baremetal (with raspberry pis) demo, but I don't know what else I could be adding to it. If you have any ideas @mcuadros @campoy, please tell me so. If not, I will send it as it is...

**Comment by campoy** [comment]
new deadline: 2018/07/16

**Comment by campoy** [comment]
That sounds like a good topic for the conference, but maybe we can try to talk a bit more about what we do at source{d} while we're at it.

Do you have the slides from the last time? (Could you also add them [here](https://github.com/src-d/conferences/blob/master/2018-cfgmgmtcamp/coreos-baremental-provisioning-terraform.md))

**Comment by rporres** [comment]
Slides url are already in that very same document you've linked 😅 

Here they are anyway: http://bit.ly/2nCCgoa

**Comment by campoy** [comment]
How I didn't see the link ... I'll blame the jet lag!

The content seems good but I'd improve two things:

1. make sure terraform (and other hashicorp products) are more prominent on the abstract and talk
2. in the talk you should spend a bit longer explaining what we do and why we do it

Other than that, LGTM

**Comment by rporres** [comment]
thx, @campoy

**Comment by mcuadros** [comment]
Yep we can use rpi for sure.

**Comment by rporres** [comment]
Talk proposal: https://github.com/src-d/conferences/pull/80

**Comment by vcoisne** [comment]
@rporres have you heard back ?

**Comment by rporres** [comment]
Yes. The talk was not accepted.

**Comment by vcoisne** [comment]
Event is over. No action items. Closing.
