### ISSUE TITLE
2018/08 - KDD London

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#67]
**URL**: http://www.kdd.org/kdd2018/

**Location**: London, England

**Dates**: 2018/08/19-23

**Expenses covered**: ?

**Topic**:  machine learning and data science

**Call for Papers**:

deadline: 2018/06/01
link: http://www.kdd.org/kdd2018/calls

**Notes**:

Appeared in https://github.com/src-d/minutes/pull/227
https://twitter.com/HamelHusain/status/991701657242161152

**Comment by vmarkovtsev** [comment]
@campoy I can submit identifier splitting to http://www.kdd.org/kdd2018/calls/view/kdd-2018-project-showcase-track-call-for-proposals

**Comment by campoy** [comment]
Hey @vmarkovtsev, did you submit anything?

**Comment by vmarkovtsev** [comment]
Nope, and I am so happy I didn't!
