### ISSUE TITLE
2018/11 - Scale By The Bay

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#68]
**URL**: http://scale.bythebay.io/

**Location**: San Francisco, CA

**Dates**: 2018/11/15-17

**Expenses covered**: unnecessary (local conf)

**Topic**:  Functional Programming, Data Engineering, Cognitive Frameworks

**Call for Papers**:

deadline: 2018/05/31
link:  http://scale.bythebay.io/cfp.html

**Notes**:

We were invited to apply personally by one of the organizers on this [tweet](https://twitter.com/ChiefScientist/status/999113908928503808).

**Comment by campoy** [comment]
Talk accepted!

**Comment by campoy** [comment]
Next steps:

- [x] prepare talk
- [x] create slides && publish them
- [x] give talk
- [ ] release recording once available

**Comment by vcoisne** [comment]
@campoy Did they share the recording ? Can you share your slides when you have minute ?

**Comment by campoy** [comment]
slides: https://docs.google.com/presentation/d/e/2PACX-1vRgitd9s2FGgN52GZIMaW8m0bA7vvr0h2ErD-xZrPl7rl9hdBmuV5y2-3HEl_Rgztp6qvCQs2ncCUNc/pub?start=false&loop=false&delayms=3000

recording still not out
