### ISSUE TITLE
2018/11 - Artificial Intelligence International Conference - Barcelona

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#72]
**URL**: http://premc.org/conferences/a2ic-artificial-intelligence

**Location**: Barcelona, Spain

**Dates**: 2018/11/21-23

**Expenses covered**: no

**Topic**:  machine learning, research

**Call for Papers**:

deadline: 2018/06/13
link: https://a2ic2018.exordo.com/

**Notes**:

I received an email from this conference and it seems like a good opportunity for the ML team to present, the trip is short.

@eiso and @vmarkovtsev, do you know anything about this conference?

**Comment by eiso** [comment]
Never heard of it.
