### ISSUE TITLE
 2018/06 - Moscow Python Meetup

### ISSUE THREAD

**Issue by zurk** [src-d/conferences#73]
**URL**: http://www.moscowpython.ru/meetup/57/

**Location**: Moscow, Russia

**Dates**: 2018/06/26

**Expenses covered**: Nothing

**Topic**: Python

**Call for Papers**: No paper, talk only.

**Notes**: I will talk about embeddings, swivel algorithm and how we use it for code analysis.

**Comment by campoy** [comment]
Hey @zurk,

I had a look at the slides and they look really good.
It'd be interesting to try and make a video out of this talk.

**Comment by zurk** [comment]
hey, cool!
here you can find original slides: https://zurk.github.io/moscow-python-06-2018/

Do you need any help from me? 
Like to translate slides into English may be? :)

**Comment by vcoisne** [comment]
@zurk Do you have an english version ? Would love to share on social media.

**Comment by zurk** [comment]
Nope, but I think I can translate it once. In the next Open Source Day, for example.

**Comment by vmarkovtsev** [comment]
@zurk ping

**Comment by campoy** [comment]
ping

**Comment by vcoisne** [comment]
@zurk ping :)

**Comment by zurk** [comment]
ok, sorry, I lost it, guys. is it fine to translate it after we release style analyzer?

**Comment by vcoisne** [comment]
@zurk Is this still something you'd like to do at some point ?

**Comment by zurk** [comment]
Yeah, but we still do not have a release for style analyzer and this is top 1 thing to do. As soon as we done here I will translate it. It should be soon

**Comment by campoy** [comment]
The style analyzer is ready to be released, so should we work on this?

**Comment by zurk** [comment]
yeah, I remember about this issue, thanks for ping anyway. :) Today we have a lot of meetings, I plan to do it tomorrow.

**Comment by zurk** [comment]
check this out! https://zurk.github.io/moscow-python-06-2018-en/

**Comment by campoy** [comment]
Thanks, @zurk!

Hey @vcoisne I'll let you handle this and make sure we add it to our social media sharing list.

**Comment by vcoisne** [comment]
Yep, on it.

**Comment by campoy** [comment]
I guess we can close this now.
