### ISSUE TITLE
2018/11 - Data Natives

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#74]
**URL**: http://datanatives.io/

**Location**: Berlin, Germany

**Dates**: 2018/11/22-23

**Expenses covered**: no
**Topic**:     ML, DS

**Call for Papers**:

deadline: N/A
link:     https://ftjournal.typeform.com/to/WPnpKC

**Notes**:

Vadim spoke on Data Natives in 2016. They make nice videos and organize well. There was bullshit spotted in the talks though.

**Comment by vmarkovtsev** [comment]
@campoy for your consideration - I can talk if you command

**Comment by campoy** [comment]
To be honest, this doesn't look very relevant to our interests.
How did you hear about it?

**Comment by vmarkovtsev** [comment]
@campoy as written in the Notes, I spoke there. It is German DS/ML conference with good org and nice swag. source{d} used to have a booth in 2016 run by @philiphave and @elenagrebe

**Comment by campoy** [comment]
If you think it's really worth it I'll approve it.
Could you point me to the video from the previous time?

**Comment by vcoisne** [comment]
@campoy https://www.youtube.com/watch?v=HMCsxpjUqRc&list=PLgPptl9CaO3z3C_hSV_Ey9F7Dw3nw2_AL 

Looks like a nice event to me. If you end up going @vmarkovtsev let me know and I will help organize a meetup at the same time.

**Comment by campoy** [comment]
The video is not great ... you can't see the slides at all.
But probably this year it will be better, one can hope.

Check with @mcuadros because I've seen he's concerned about the bandwidth spent by the ML team at conferences. I'd rather keep your appearances at conferences for larger impact ones.

**Comment by vmarkovtsev** [comment]
```
Dear Vadim ,

My name is Christine Pracht, and I am a member of the team at Data Natives.
I am pleased to announce the fourth and exciting edition of Data Natives Berlin
taking place on the 22-23 of November 2018!

As a speaker from one of our previous events, we would like to invite you to fill out
our invitation-only non-transferable speaker form. The form will give us a great overview
on the topics you would like to contribute to this year and to schedule the talk
accordingly. Please find the form here - The deadline for submission is August 1. 

We would love to have you involved, and to once again showcase your expertise at this year’s event.
I am happy to set up a call to answer any questions. I look forward to hearing from you! 

Best regards, 

Christine
```

**Comment by mcuadros** [comment]
@vmarkovtsev you can speak at the conference if, you don't need to do any effort to create the content for it and is strictly related to the style code analysis.

**Comment by campoy** [comment]
Hey @vmarkovtsev did you apply at all?

**Comment by vmarkovtsev** [comment]
I did not apply, we can close.
