### ISSUE TITLE
2018/11 - Devoxx Belgium

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#75]
**URL**: https://devoxx.be/

**Location**: Antwerpen, Belgium

**Dates**: 2018/11/12-16

**Expenses covered**: covered by GDE

**Topic**:  software

**Call for Papers**:

deadline: 2018/07/06
link:  https://dvbe18.confinabox.com/

**Notes**:

They make nice videos. "Deep Learning without a Phd" was presented there.

**Comment by vmarkovtsev** [comment]
@campoy for your consideration - waiting for your command

**Comment by campoy** [comment]
Totally down for this!

**Comment by vmarkovtsev** [comment]
Considering this as approved.

**Comment by vcoisne** [comment]
Great conference +1 

@vmarkovtsev let me know when confirmed and if you're up for speaking at a meetup at the same time.

**Comment by campoy** [comment]
Hey @vmarkovtsev, did you propose anything?

**Comment by vmarkovtsev** [comment]
I did not propose. We can close.
