### ISSUE TITLE
2018/10 - PyCon France

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#76]
**URL**: https://www.pycon.fr/2018/en

**Location**: Lille, France

**Dates**: 2018/10/04-07

**Expenses covered**: no

**Topic**:  Python

**Call for Papers**:

deadline: N/A
link: https://cfp-2018.pycon.fr/cfp/

**Notes**:

For @warenlg or @r0mainK

**Comment by campoy** [comment]
SGTM, feel free to apply

**Comment by vmarkovtsev** [comment]
@r0mainK you could talk about the PGA deduplication there.

**Comment by r0mainK** [comment]
@vmarkovtsev  too late for the party :/ I just checked on the second link, the only "Talk Category" left is "Codage Participatif", french for Collective Coding. So I would have to demo `apollo` which could also be cool, but I saw on the first link that all of these kind of events are scheduled on the two first days, which are week days - I'll be in class. 

Might be worth to try and contact them to see if I could slip in the week-end, but from their [temporary WE planning](https://www.pycon.fr/2018/images/program_fr_15082018.pdf) they seem kind of overbooked already

**Comment by vmarkovtsev** [comment]
That's a pity.
