### ISSUE TITLE
2018/11 - PiterPy

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#77]
**URL**: https://piterpy.com/

**Location**: Saint Petersburg, Russia

**Dates**: 2018/11/02-03

**Expenses covered**: no

**Topic**:   Python

**Call for Papers**:

deadline: 2018/11/01
link:  https://piterpy.com/speaker#form

**Notes**:

Russians recommended. @Guillemdb spoke there and liked it

**Comment by campoy** [comment]
What's the topic of the talk you're planning to give?
Also, is the deadline really the day before the conf starts? 😕

**Comment by Guillemdb** [comment]
Nope, they don't have a definite deadline. Instead, the call for papers finishes when all the talk slots they have are covered, so the sooner you apply, the better.

**Comment by campoy** [comment]
Interesting, @vmarkovtsev what would the topic be?
it's a very general conference (and my Russian is not good enough to judge further than that)

**Comment by vcoisne** [comment]
ping @vmarkovtsev ?

**Comment by vmarkovtsev** [comment]
I have to skip - too many Google events already on my list. Maybe @EgorBu or @m09 can participate?

**Comment by vmarkovtsev** [comment]
Also tagging @warenlg @zurk 

We should speak about smth related to our Analyzer framework.

@warenlg particularly can speak about his diploma (cool pics!)

**Comment by vmarkovtsev** [comment]
@campoy Can you please fix the stupid bot

**Comment by campoy** [comment]
Hey, the bot is not stupid! It just enjoys talking to you, man.
I added fixing it to my todo list, but also to the hacktoberfest list, maybe someone fixes it before I get to it?

**Comment by zurk** [comment]
Sorry guys, I miss that you tag me here. I should be in Moscow on 2 Nov. Unfortunately, I cannot attend.

**Comment by m09** [comment]
For some reason I also missed the tag. I can attend but it's maybe a bit early since our style analyzer (which would probably be the subject of the talk) doesn't target python yet. WDYT @vmarkovtsev?

**Comment by vmarkovtsev** [comment]
AFAIK speaking about Python in the context of any code analysis is nice, and the people are going to like it anyway. E.g. I remember one guy who talked about web services in Erlang and nobody complained.

But Hugo you are already doomed because no way you can get a Russian visa within the remaining two weeks.

**Comment by m09** [comment]
That settles it then :/

**Comment by campoy** [comment]
Ok, then closing this.
