### ISSUE TITLE
2018/05 J on the Beach

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#8]
**URL**: https://jonthebeach.com/

**Location**: Malaga, Spain

**Dates**: 2018/05/23-25

**Expenses covered**:

We offer basic accommodation during the event. Exceptionally we will also cover the flight only for freelance developers or those working in startups not funded by other companies.

**Topic**: 

- Distributed Systems
- Use cases related to Big Data-Architectures-development process
- Machine learning / algorithms
- JVM & .Net developments
- Analytics & Data Visualisation
- Databases
- Functional Programming
- IoT and embedded

**Call for Papers**:

- deadline: 2018/01/31
- link:  https://www.papercall.io/jotb18

**Notes**:

Easy to get from Madrid, so probably worth having some of us applying.

**Comment by bzz** [comment]
As discussed, I think it is a relevant place to talk about src-d Data Retrieval pipeline of finding/collection/storing/processing all Git repositories in the world.

Probably, am going to submit a talk there.

**Comment by bzz** [comment]
Have submitted the talk "The Anatomy of a Large-Scale Git Repository Collection Pipeline".

**Comment by bzz** [comment]
Would be happy to change label to `phase:waiting` but do not have enough permissions. 

Ping @campoy. Also, let me know if a PR needs to be submitted or something like that.

**Comment by campoy** [comment]
I think you should be able to change it now

**Comment by bzz** [comment]
The talk was not accepted, but because of that they gave us 50% discount on all the tickets and we have people going there at src-d/office#42.
