### ISSUE TITLE
2019/02 FOSDEM

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#81]
**URL**: fosdem.org

**Location**: Brussels, Belgium

**Dates**: 2019/02/02-03

**Expenses covered**: no

**Topic**:  OSS

**Call for Papers**:

deadline: TBA
link: TBA

**Notes**:

Last year we ran the Go and Language Analysis devrooms.
We should do the same this year, or maybe change Language Analysis to ML on Code?

**Comment by campoy** [comment]
CfP is now open, time to apply!

**Comment by campoy** [comment]
Room proposal sent for Go devroom:

```
Devroom Request for FOSDEM 2019

We acknowledge that we have received your request for the following devroom.
After we review all devroom requests, we will inform you accordingly via email.

Title: Go
Coordinator: Francesc Campoy
Coordinator email: campoy@golang.org
Secondary contact: Maartje Eyskens
Secondary email: maartje@innovatete.ch

Description:
For the fifth year in a row, the Go community has a room at FOSDEM.
The time will be spent talking about Go projects and interesting topics that spark a conversation among the attendees.

We'll cover what's new in the latest Go release, including go modules, while keeping an eye on new and old projects.

Coordinator's affinity to the topic of the devroom:
I used to be the Developer Advocate for the Go team at Google until I recently left the team.
I'm still very involved with the community and have organized and MCed at this room many times brefore.

Why does it fit FOSDEM
Go is an Open Source programming language with a very active community, this will be the 5th year in a row and we're looking to celebrate with the many gophers flying all around the world to attend this event.

Relevant URLs:
previous year: https://www.youtube.com/watch?v=iR7LPAXWfmw&list=PLtLJO5JKE5YCYgIdpJPxNzWxpMuUWgbVi

Timeslot:
Full day

Special requirements:
This room should not happen at the same day as the "Language Analysis" devroom also organized by me.
```

**Comment by campoy** [comment]
Also room proposal sent for ML on Code devroom:

```
Devroom Request for FOSDEM 2019

We acknowledge that we have received your request for the following devroom.
After we review all devroom requests, we will inform you accordingly via email.

Title: ML on Code
Coordinator: Francesc Campoy
Coordinator email: campoy@golang.org
Secondary contact: Victor Coisne
Secondary email: vcoisne@sourced.tech

Description:
Previously known as Language Analysis Devroom during FOSDEM 2018, this room covers the topics of Machine Learning applied to Language Analysis, commonly known as ML on Code.

Possible topics include assisted code reviews, language agnostic program representation, bug prediction, and automated program repairing.

Other conferences covering these topics include http://www.msrconf.org/.

Coordinator's affinity to the topic of the devroom:
I am the VP of Developer Relations at source{d} (sourced.tech), the leader of the ML on Code field.
I have good relationships with many of the most influential researchers in the field, including academia and industry individuals, which would be an amazing addition to the FOSDEM lineup.

Why does it fit FOSDEM
Open Source can benefit from the application of Machine Learning, since it can provide an opportunity to scale essential tasks such as code reviews, helping those with deep knowledge empower those that are learning.

Last year we managed the Language Analysis devroom for the first time and it was very successful. We saw that many of the proposals included some kind of ML so we decided it was a great opportunity to adapt to the community.

Relevant URLs:
a conference with similar topics: http://www.msrconf.org/
blog on our participation at FOSDEM last year: https://blog.sourced.tech/post/fosdem-2018/

YouTube playlist from last year: https://www.youtube.com/playlist?list=PL5Ld68ole7j2H1SnyhDg7DI0fgh0GNuez
note: we had some serious AV issues

Timeslot:
Full day

Special requirements:
This should not happen on the same day as the Go devroom, as the organizers will be hosting both.
```

**Comment by m-murad** [comment]
@campoy
The conference covers expenses (both travel and accommodation). Can you update the issue description.

**Comment by campoy** [comment]
Hey @bzz, it seems you managed the Language Analysis room last year and that it was proposed in collaboration with others.

Would you have time to discuss exactly who was involved so we can repeat that this year?

**Comment by bzz** [comment]
> Would you have time to discuss exactly who was involved so we can repeat that this year?

sorry for delay @campoy, yes, sure. I know @dennwc was also interested to get involved. 

Last year, together with LA team we were inviting many people from different projects/communities https://github.com/src-d/backlog/issues/1010#issuecomment-329136876 to co-organize and support DevRoom effort to show that it's indeed a community.

**Comment by kuba--** [comment]
Hey deadline-reminder! you are annoying ;)

**Comment by bzz** [comment]
Thank you @kuba-- !

Here is the link to my answer https://github.com/src-d/conferences/issues/81#issuecomment-417577380 if somebody else is not keep on un-rolling 400 comments thread 🤖 

Good example of what to avoid in lookout 😹

**Comment by bzz** [comment]
and here we go https://github.com/src-d/conferences/issues/81#issuecomment-417611806

**Comment by kuba--** [comment]
@campoy - I'm closing this issue (we can reopen later), because it's still spamming

**Comment by campoy** [comment]
Reopened issue after removing `reminder` line from the original issue
That should fix it for now

**Comment by kuba--** [comment]
I propose to give a talk in DB dev-room about "how we implemented indexes for git database using  bitmaps and key-value storage"

In other words:
- general introduction to gitbase (what it is and how it works)
- where indexes are used and how
- deep dive into design (pilosa bitmaps + boltdb mapping)
- current limitations

**Comment by campoy** [comment]
Make sure you propose the talk following the instructions [here](https://medium.com/@maartjeme/go-devroom-cfp-fosdem-2019-60616770f3a5), @kuba--

**Comment by campoy** [comment]
Last item is to release two blog posts covering the talks of each devroom + links to videos and slides.

@vcoisne will release them next week.

**Comment by bzz** [comment]
@vcoisne here is the blog post mentioned above https://blog.sourced.tech/post/fosdem-2018/

Would be happy to help/review this year's draft if needed.
I guess it would make sense to mention GitMerge and @jfontan talk somehow as well.
