### ISSUE TITLE
2018/11 Meetup around Open Data Science Conference SF

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#82]
**URL**: https://www.meetup.com/MLonCode/events/255617635/

**Location**: London, UK and San Francisco, CA

**Dates**: 

San Francisco, CA - Nov 1, 2018

**Expenses covered**: 

Maybe

**Topic**:    ML, AI

**Notes**:

Lots of very legit people are following / attending

**Comment by vcoisne** [comment]
@campoy Happy to submit on your behalf if you can make the SF edition ?

**Comment by vcoisne** [comment]
Submit for Boston and organize a meetup at the same time as SF.

**Comment by campoy** [comment]
@vcoisne to update this with new plans

**Comment by vcoisne** [comment]
updated

**Comment by vcoisne** [comment]
Event is done. Video & slide published and promoted.
