### ISSUE TITLE
2018/12 - NIPS (Neural Information Processing Systems) 2018

### ISSUE THREAD

**Issue by marnovo** [src-d/conferences#83]
# 2018/12 - NIPS (Neural Information Processing Systems) 2018

**URL**: https://www.nips.cc/Conferences/2018/Dates

**Location**: Montréal, Canada

**Dates**: 2018/12/03–08

**Expenses covered**: fees covered for speakers: transportation, hotel, etc

**Topic**: Machine Learning

**Call for Papers**:

deadline: 2018/05/18
link:     https://cmt3.research.microsoft.com/NIPS2018/

Still possible to submit demonstrations until Sep 16, though:
https://nips.cc/Conferences/2018/CallForDemonstrations

**Notes**:

Most well known "general-purpose" ML conference. 
We have attended in the past. cc/ @eiso @vmarkovtsev 

Registration starts on Sep 4 (and usually sells out quickly)

**Comment by vmarkovtsev** [comment]
Canada - all the European employees are out as in the last year. Maybe @campoy can visit...

**Comment by vcoisne** [comment]
@campoy also happy to submit for you if you can make it ?

**Comment by marnovo** [comment]
@marnovo:
> Registration starts on Sep 4 (and usually sells out quickly)

@NipsConference:
> #NIPS2018 The main conference sold out in 11 minutes 38 seconds
https://twitter.com/NipsConference/status/1037011898640752641

As for attending, I could. But that entails being allowed to attend, heh.
Nonetheless, we have until this Sunday to submit a demonstration.

**Comment by campoy** [comment]
Passing this year. 2019 to be considered.
