### ISSUE TITLE
2018/11 - ESEC/FSE 2018

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#85]
**URL**: https://2018.fseconference.org/home

**Location**: Lake Buena Vista, Florida, United States

**Dates**: 2018/11/4 - 2018/11/9

**Expenses covered**: You can apply for support

**Topic**: ML for Software Engineering

**Call for Papers**: Closed

**Deadline:** next year CFP by 2019/2

**Notes**:
Seems like a great conference to attend to engage with Academia
We could fit in different tracks i.e workshops, Research Papers, Demonstrations, New ideas, etc

**Comment by vmarkovtsev** [comment]
ACM Joint European Software Engineering Conference and Symposium takes place in Florida... Weird. @warenlg should be somewhere near your house.

**Comment by warenlg** [comment]
It's colocated with the workshop Prem Devanbu advertized us in Oxford, remember NL4SE https://nl4se2018.github.io/ And the deadline of the CFP for short papers is 31st August
Yes my father lives in Tampa, 1h driving from Lake Buena Vista

**Comment by vmarkovtsev** [comment]
Is it possible to submit our id split paper I wonder.

**Comment by campoy** [comment]
Should we attend this year? Is this a well known conference for our domain, similarly to MSR?
@vmarkovtsev

**Comment by campoy** [comment]
I guess no one is going.
