### ISSUE TITLE
2018/09 -  ICSME

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#86]
**URL**: https://icsme2018.github.io/

**Location**: Madrid, Spain

**Dates**: 2018/09/24 - 2018/09/28

**Expenses covered**: No travel required

**Topic**:    Software Maintenance and Evolution (ICSME) is the premier international forum for researchers and practitioners from academia, industry, and government to present, discuss, and debate the most recent ideas, experiences, and challenges in software maintenance and evolution.

**Call for Papers**: Sponsoring gives us a talk

**Notes**:

Opportunities to do a 20m presentation in the pre-reception Tuesday in the URJC building at Manuel Becerra. Afterwards there will be some food and time for demos, informal chat, etc.

Get talk title and abstract about source{d} + speakers. 
+ demo afterwards ?

Sponsoring an MSR-like get-together on Wednesday (expected RSVP 150 people). 
9 to 11pm. Eventbrite page for registration. 

Budget 2K EUR

Timeline:

- [x] Initial discussion via email 
- [x] Call with Gregorio on 8/28 to get additional details
- [x] Confirm availability of the team for presentation on Tuesday and drinks on Wednesday
- [x] @estherrgarcia looking into potential after party venue availability & costs
- [ ] Confirm talk + get-together details & start promoting

**Comment by estherrgarcia** [comment]
I have found a venue for the get-together on Wednesday, 26th. 
It would be the new Irish Pub in Calle Principe -- 7 min walking from Circulo de Bellas Artes (ICSME) -- O'Brian (the old O'neill's). It's big enough for 150 people. There are two floors, we would use the downstairs one. That Wednesday there is LaLiga, so they expect people attending to Barcelona game an 8 pm and Real Madrid game at 10 pm. 
We would have a bar only for us. As the supervisor used to work with me, he will give us a good discount.
The venue is on renovations right now but it will be ready soon.  

Things we have to decide:
1. Is the event at 21.00 or earlier? I've checked the conference schedule and looks that the conference finishes around 6 pm 
2. We want to have food at the venue. Food to have dinner or food to have a snack.
2. Are we going to give tokens to people to be changed for a beer? If we are, 2 is ok? also, we need to order them. 
3. Are we going to send an individual invitation?
4.  Are we going to control the attendees? If we are going to do it, we have to decide how. We can do it on the door with the Eventbrite code. 
5. Will we need anything else special? Mkt stuff?

**Comment by vcoisne** [comment]
Thanks a lot @estherrgarcia ! Any idea of costs ?

1. It would start at 8:30 at the earliest, there is the official reception before. 
2. Light snacks is fine. Nothing fancy. 
3. Yes 2 beers is ok. We can order the tokens. 
4. Yes the organizer of the conference will send an invitation & promote the registration via eventbrite
5. Yes via eventbrite scan codes is fine. 
6. Yes stickers only. Do we have a roll up banner in the office ?

**Comment by estherrgarcia** [comment]
The cost depends on the number of people. If we are 150 I can push them more to get a better discount than if we are 100. It would be around the 2000 euros of budget you said. 

1. I will tell the venue 20.30 to be ready! 
2. Np! I will send you the details.
3. Perfect. I will ask @ricardobaeta. I don't know if we can to use the old design or a new one. 
4. Are you going to prepare the Eventbrite event? Let me know if you need anything. 
5. That means we would need someone at the door scanning the codes and giving the tokens. 
6. We have some roll up. I will send you photos to decide if we want to use them or not.

**Comment by vcoisne** [comment]
Perfect thank you @estherrgarcia 

1 and 2. Please confirm with them, we'll know final RSVP number as we get closer to the event
3. Thanks 
4. Yes here https://www.eventbrite.com/e/icsme-after-party-sponsored-by-sourced-tickets-49955465141
5. @bzz and @jfontan will be attending. Do you think you'll be able to attend ?
6. Per our Slack, lets use the old one or make a new one if we have time

Thanks again for all your help with this!

**Comment by vcoisne** [comment]
Completed.
