### ISSUE TITLE
2018/09 - GoWayFest 2.0

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#87]
**URL**: GoWayFest 2.0

**Location**: Minsk, Belarus

**Dates**: 2018/09/28-29

**Expenses covered**: transportation is covered, maybe the hotel too

**Topic**: Go

**Call for Papers**:

deadline: N/A
link: N/A

**Notes**:

Contacted privately by the organizers. Offered them to repeat the Francesc's talk on Gophercon or tell about how cool Hercules is ([ping](https://github.com/src-d/blog/pull/239)). They have chosen Hercules.
So maybe it is the time to add Hercules as a UDF inside gitbase and present them together - I will need some participation of the Data Retrieval then.

**Comment by vcoisne** [comment]
@vmarkovtsev have you heard from them since then ? How many attendees ?

**Comment by campoy** [comment]
ping, @vmarkovtsev ?

**Comment by vmarkovtsev** [comment]
They paid for the plane and the hotel, I am going. Should be around 200 people. It appeared to be a very well-known Go event in the CIS region.

**Comment by vmarkovtsev** [comment]
The talk was given. http://vmarkovtsev.github.io/gowayfest-2018-minsk/

**Comment by campoy** [comment]
Awesome!
