### ISSUE TITLE
2018/10 - Nantes ML meetup

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#88]
**URL**: https://github.com/nantes-machine-learning-meetup/NMLM

**Location**: Nantes, France

**Dates**: 2018/10/01

**Expenses covered**: no

**Topic**: ML

**Call for Papers**:

deadline: N/A
link: N/A

**Notes**:

This meetup is co-organized by our @m09.

**Comment by vcoisne** [comment]
Would @m09 be giving the talk ?

**Comment by m09** [comment]
No it would be @vmarkovtsev. The event page is up https://www.meetup.com/Nantes-Machine-Learning-Meetup/events/254214916/.

**Comment by vmarkovtsev** [comment]
The talk was given. http://vmarkovtsev.github.io/tfjs-2018-nantes/

**Comment by campoy** [comment]
Please send a PR adding the slides to your proposal https://github.com/src-d/conferences/pull/91/files

**Comment by vcoisne** [comment]
Ping @vmarkovtsev

**Comment by vmarkovtsev** [comment]
Done
