### ISSUE TITLE
2018/11 - DevFest Krasnodar

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#89]
**URL**: https://www.meetup.com/meetup-group-IfBrKrSH/events/253269181/

**Location**: Krasnodar, Russia

**Dates**: 2018/11/17

**Expenses covered**: Google pays for everything if you are a GDE

**Topic**: Google tech

**Call for Papers**:

deadline: N/A
link: N/A

**Notes**:

Contacted privately by the organizers. Estimated attendance: 450.

**Comment by vcoisne** [comment]
@vmarkovtsev looks like 450 is the total capacity, the group only has 288 members so I don't think turn out will be great.

**Comment by vmarkovtsev** [comment]
There will be people from the outside of the group since these events are rare in that region.

**Comment by vcoisne** [comment]
Is this confirmed @vmarkovtsev ?

**Comment by vmarkovtsev** [comment]
Confirmed and paid by Google.

**Comment by vcoisne** [comment]
@vmarkovtsev was that the same slides as the other DevFest on tensorflow.js ? Want to submit a PR so that we can close this issue ?

**Comment by campoy** [comment]
ping

**Comment by vmarkovtsev** [comment]
The PR has already been merged https://github.com/src-d/conferences/pull/93 and we can close.

**Comment by vcoisne** [comment]
Closing.
