### ISSUE TITLE
2018/07 OSCON

### ISSUE THREAD

**Issue by campoy** [src-d/conferences#9]
**URL**: https://conferences.oreilly.com/oscon/oscon-or

**Location**: Portland, OR USA

**Dates**: 2018/07/16-19

**Expenses covered**:

If your proposal is chosen, would you need assistance with hotel or travel related expenses (for example, because you are self-employed)? Please note: Your answer to this question will have no impact on the committee’s review of your proposal.

**Topic**:

- Software Developer/Engineer
- Architect / Technical Lead
- System Engineer
- DevOps Engineer
- VP/Director
- Engineering Manager
- Data Scientist / Analyst
- CXO
- Product / Project Manager
- Consultant
- Community Manager
- Sales / Business Development
- Professor / Academic
- IT Manager

**Call for Papers**:

- deadline: 2018/01/30
- link:  https://conferences.oreilly.com/oscon/oscon-or/public/cfp/615

**Notes**:

This is one of the most important conferences in the Open Source world.
Definitely worth attending and running a Birds of a Feather.

**Comment by campoy** [comment]
Workshop proposal accepted!

**Comment by bzz** [comment]
:tada: Awesome, wich workshop are we running there?

**Comment by bzz** [comment]
> a full day workshop for Go tooling, this workshop will cover the third chapter of github.com/campoy/go-tooling-workshop

Not sure if that's still the case, but that explains it well, just missed it from PR

**Comment by campoy** [comment]
Sorry, totally missed this comment!
Yeah, I'm running a Go workshop and using the opportunity to run a MLonCode BoF
