### ISSUE TITLE
2018/12 - DevFest Lisbon

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/conferences#90]
**URL**: https://www.meetup.com/gdglisbon/events/254067020/

**Location**: Lisbon, Portugal

**Dates**: 2018/12/08

**Expenses covered**: Google pays for everything if you are a GDE

**Topic**: Google tech

**Call for Papers**:

deadline: N/A
link: N/A

**Notes**:

Contacted privately by the organizers.

**Comment by vcoisne** [comment]
@vmarkovtsev Does not look like they have big turn out at their meetups. Not sure it's worth your time.

**Comment by vmarkovtsev** [comment]
The group has more than 1,800 members... I am afraid I have to do this low-level work so that my GDE status does not expire. The alternative is to write blog posts, but that's much more time consuming.

**Comment by vcoisne** [comment]
@vmarkovtsev that's a quick / cheap flight from Madrid so if you think turn out is going to be good, I would say go for it.

**Comment by campoy** [comment]
@vmarkovtsev to start booking tickets and organizing talk

**Comment by campoy** [comment]
Could you also verify whether the trip/hotel is paid by GDE?

**Comment by vmarkovtsev** [comment]
@campoy It is paid 100%. The talk is already settled and I just need to file another GDE approval.

**Comment by campoy** [comment]
That's awesome (we're working on DevRel budget)

**Comment by vcoisne** [comment]
@vmarkovtsev how did the talk go ? was that the same slides as the other DevFest on tensorflow.js ?

**Comment by campoy** [comment]
ping

**Comment by vmarkovtsev** [comment]
The PR has already been merged https://github.com/src-d/conferences/pull/94 and we can close.

**Comment by vcoisne** [comment]
Closing then.
