### ISSUE TITLE
2018/12 - ML conference 

### ISSUE THREAD

**Issue by EgorBu** [src-d/conferences#97]
# 2018/12 -  ML conference 

**URL**: https://mlconference.ai

**Location**: Berlin, Germany

**Dates**: 2018/12/05-07

**Expenses covered**: we need to discuss with organizers

**Topic**:    ML

**Call for Papers**:

**Notes**:
I participated in ML conference in Munich - and it was a good conference with a lot of people with relevant ML background. They want me to make 25 minutes talk about MLonCode.

**Comment by vcoisne** [comment]
@EgorBu I think this is a great opportunity. Big +1 from me. We can also organize a meetup at the same time. Would be great to get more info on speaker expenses before accepting.

**Comment by EgorBu** [comment]
Updated expenses.

**Comment by EgorBu** [comment]
Link to talk: https://mlconference.ai/machine-learning-advanced-development/machine-learning-on-source-code/

**Comment by campoy** [comment]
Speaker already announced https://mlconference.ai/?gclid=EAIaIQobChMInqaJ9u_W3QIVkJJ-Ch0ozQLREAEYASAAEgLTnvD_BwE

**Comment by vcoisne** [comment]
@EgorBu how did the talk go ? Can you share your slides / video recording by submitting a PR to this repo ?

**Comment by campoy** [comment]
ping @EgorBu

**Comment by EgorBu** [comment]
Sorry, missed your messages.
[Slides](https://docs.google.com/presentation/d/1THcPCLlucV7Q7EKYCKn1NFu62RjTrN-4nbOI_t0Ga3A) and I haven't received any video.
The talk was average - too much material & there were some issues with equipment and no time gap between presentations (there was a gap after lunch but it was occupied by people who should make speeches before me).

**Comment by campoy** [comment]
Ok, don't worry about the recording then.

Just send a PR adding the link to the slides on the proposal.

Thansk, @EgorBu !

**Comment by campoy** [comment]
Ping, @EgorBu

**Comment by vcoisne** [comment]
@EgorBu did you publish the slides somewhere ? If not, can you send them to me on slack and I will post & close this issue ?

**Comment by vcoisne** [comment]
This is an old issue, content is out dated by now. closing.
