### ISSUE TITLE
2019/02 - Saner 2019

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#99]
# 2019/02 - Saner 2019

**URL**: https://saner2019.github.io/

**Location**: Hangzou, China

**Dates**: (2019/02/24-27)

**Expenses covered**: maybe

**Topic**:     ML, 

**Call for Papers**:

Tool demo track deadline: 2018/11/28
Workshop track deadline: 2018/09/30

link:     https://easychair.org/account/signin.cgi?key=78122810.7aDI5VkiLVvu0dJu

**Notes**:

Could be an opportunity to meet with local community members. Hangzhou is an active tech hub.

**Comment by campoy** [comment]
I think this is worth the effort to open up to the Chinese market.

What do you think,  @eiso? I could attend after FOSDEM.

**Comment by campoy** [comment]
After sync up decided not to go, for now.
